<?php
namespace Framework\Pipeline;


use Framework\Http\RequestInterface;

class RouterHandler extends Handler
{
    public function handle($data = null)
    {
        /**@var $data RequestInterface*/
        d($data->path());
        return parent::handle($data); // TODO: Change the autogenerated stub
    }
}